### ISSUE TITLE
CLI & GUI Compilation Targets

### ISSUE THREAD

**Issue by Zeddicus414** [MichalGniadek/klask#29]
When I make tools using Python's Gooey library, I usually end up wanting a CLI version for myself (and maybe other power-users) and then a GUI for everyone else in the office.

If it's possible to get both a CLI & GUI binary from the same source code, it would be helpful to have an example.

Is this easily possible with conditional compilation or some other method?

**Comment by MichalGniadek** [comment]
Hi! You can use cargo to make multiple binaries. So you could make one cargo project with a library that contains most of your code and then two small binaries, that either call the clap directly or use klask.

**Comment by Zeddicus414** [comment]
Ahh, that makes tons of sense. I learned something today!

For anyone asking the same question, this SO question has a concise example:
https://stackoverflow.com/questions/36604010/how-can-i-build-multiple-binaries-with-cargo

Thank you.

**Comment by arifd** [comment]
Hi @MichalGniadek, I thought somewhere it was planned, to be able to create a single binary where if no command line arguments are supplied, then the Klask GUI would appear, otherwise, args would get passed to Clap, is this feature still on the roadmap? Or did I just hallucinate this feature altogether?
