### ISSUE TITLE
Missleading Documentation

### ISSUE THREAD

**Issue by rademonster** [MichalGniadek/klask#34]
Klask is awesome. Its been a huge boon to productivity. Thanks for building this. 

I have one complaint :)

The documentation for app_run states:

"Call with an [App](https://docs.rs/clap/3.0.0/x86_64-unknown-linux-gnu/clap/build/app/struct.App.html) and a closure that contains the code that would normally be in main."

which leads one to belive that they should have some function that would do what the main function should do in a simple cli. Instead it looks like klask forks off a child process and passes it the arguments that the user entered in the UI. I skimmed the code, looks like there are some environment variables being set to prevent infinite recursion. Its probably a good idea to document changes to the environment as well.

After reading the documentation I wrote the following code to boot the gui if the user did not provide required arguments. I had no idea that the main was essentially being called twice and that only the second call to routine was ever called. I'd file a pr to tweak this but I don't fully understand whats going on yet. It seems like sometimes run_derived does call the closure, and other times it does not. 

```rust

// clap derive on this
struct Opt{
}

// actuall processing using arguments
fn routine(opt: &Opt){};

fn main() {
    match Opt::try_parse(){
        Err(e) if e.kind == clap::ErrorKind::MissingRequiredArgument => {
            println!("{}", e);
            klask::run_derived::<Opt, _>(Settings::default(), |matches| match routine(&matches) {
                Ok(_) => {}
                Err(e) => eprintln!("Error: {}", e),
            });
        },
        Err(e) => e.exit(),
        Ok(opt) => match routine(&opt) {
            Ok(_) => {}
            Err(e) => eprintln!("Error: {}", e),
        },
    }
}
```

Thanks again.

**Comment by MichalGniadek** [comment]
Hi!
I run the binary twice so that I can easily intercept println/ stdout and also pass in files/ text to stdin. The idea was to make it as painless as possible to convert a CLI app to GUI, without changing any of the main application code.
 
Klask works like this:
1. User runs the binary, there's no `CHILD_APP_ENV_VAR` environment variable ⇾ don't run any of the user code, just display GUI.
2. User presses "Run" in the GUI ⇾ run the binary, with `CHILD_APP_ENV_VAR` and intercept stdin/ stdout.
3. Binary is run with `CHILD_APP_ENV_VAR` ⇾ run the user provided closure.

Thanks for pointing out that this isn't documented, that's definitely an issue.

Ability to run GUI if there are no flags provided was requested multiple times. I think I tried it at the very beginning of working on klask, but from what I can remember there were some problems. I will definitely have to revisit this, but I don't have much time right now, unfortunately.
